[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "@uma/=lib/protocol/packages/",
  "@openzeppelin/=lib/openzeppelin-contracts/",
]

solc_version = "0.8.24"
evm_version = "shanghai"
via_ir = true

[rpc_endpoints]
goerli = "${ETH_RPC_URL}"
mainnet = "${ETH_RPC_URL}"
arbitrum = "${ETH_RPC_URL}"

[etherscan]
goerli = { url = "https://api-goerli.etherscan.io/api", key = "${ETHERSCAN_API_KEY}", chain = 5 }
mainnet = { url = "https://api.etherscan.io/api", key = "${ETHERSCAN_API_KEY}", chain = 1 }
arbitrum = { url = "https://api.arbiscan.io/api", key = "${ETHERSCAN_API_KEY}", chain = 42161 }

[fmt]
tab_width = 2
